### ISSUE TITLE
AttributeError on fitworkregion button press

### ISSUE THREAD

**Issue by ajz3d** [handcraftedcc/SDFModeler#4]
Hello Dominik,

I think there are some problems with _Fit Working Region_ button. Whenever it's pressed, it throws the following exception:

```
Traceback (most recent call last):
  File "dom::Sop/SDFM_Assembler::1.24/fitworkregion", line 1, in <module>
  File "/opt/hfs20.5.445/houdini/python3.11libs/hou.py", line 56472, in __getattr__
    return _hou.HDAModule___getattr__(self, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'module' object has no attribute 'fitWorkRegion'
```

Other parameters from _Working Region_ folder seem to be working fine.

P.S. Thanks for making this fantastic package.

**Comment by wywarren** [comment]
If you're using v1.24, it can be patched in from v1.23 to fix the error.
```
def fitWorkRegion(self):
    childnode = self.node("READ_bboxfit")
    center = childnode.geometry().attribValue("center")
    size = childnode.geometry().attribValue("size")
    
    self.parm("tx").set(center[0])
    self.parm("ty").set(center[1])
    self.parm("tz").set(center[2])   
    self.parm("sizex").set(size[0])
    self.parm("sizey").set(size[1])
    self.parm("sizez").set(size[2]) 
    self.parm("scale").set(1) 
```

I have it refactored using the new lowercase under score function naming convention in 1.24 on my fork at the moment. Although I'm currently working off of the hda from the release and renamed it to hdalc after the push.
